- name: Install docker and docker-compose pip
  pip:
    name:
      - docker
      - docker-compose

- name: Git clone
  git:
    repo: "{{ git_repository }}"
    dest: "{{ deployment_path }}"
    version: "{{ git_branch }}"

- name: Run `docker-compose up`
  docker_compose:
    project_src: "{{ deployment_path }}"
    build: yes
    debug: yes
